//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActividadWCF
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductResponse", Namespace="http://schemas.datacontract.org/2004/07/ActividadWCF")]
    public partial class ProductResponse : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool IsApprovedField;
        
        private string ProductReferenceField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsApproved
        {
            get
            {
                return this.IsApprovedField;
            }
            set
            {
                this.IsApprovedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductReference
        {
            get
            {
                return this.ProductReferenceField;
            }
            set
            {
                this.ProductReferenceField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/ActividadWCF")]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string NameUserField;
        
        private string PasswordField;
        
        private string RequestField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NameUser
        {
            get
            {
                return this.NameUserField;
            }
            set
            {
                this.NameUserField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password
        {
            get
            {
                return this.PasswordField;
            }
            set
            {
                this.PasswordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Request
        {
            get
            {
                return this.RequestField;
            }
            set
            {
                this.RequestField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Product", Namespace="http://schemas.datacontract.org/2004/07/ActividadWCF")]
    public partial class Product : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string DescriptionField;
        
        private int IDCategoryField;
        
        private int IDProductField;
        
        private string NameProductField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDCategory
        {
            get
            {
                return this.IDCategoryField;
            }
            set
            {
                this.IDCategoryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDProduct
        {
            get
            {
                return this.IDProductField;
            }
            set
            {
                this.IDProductField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NameProduct
        {
            get
            {
                return this.NameProductField;
            }
            set
            {
                this.NameProductField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IProductService")]
public interface IProductService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/InsertProduct", ReplyAction="http://tempuri.org/IProductService/InsertProductResponse")]
    ActividadWCF.ProductResponse InsertProduct();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/InsertProduct", ReplyAction="http://tempuri.org/IProductService/InsertProductResponse")]
    System.Threading.Tasks.Task<ActividadWCF.ProductResponse> InsertProductAsync();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/Authenticate", ReplyAction="http://tempuri.org/IProductService/AuthenticateResponse")]
    bool Authenticate(ActividadWCF.User user);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/Authenticate", ReplyAction="http://tempuri.org/IProductService/AuthenticateResponse")]
    System.Threading.Tasks.Task<bool> AuthenticateAsync(ActividadWCF.User user);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/GetProducts", ReplyAction="http://tempuri.org/IProductService/GetProductsResponse")]
    ActividadWCF.Product[] GetProducts(ActividadWCF.User user);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/GetProducts", ReplyAction="http://tempuri.org/IProductService/GetProductsResponse")]
    System.Threading.Tasks.Task<ActividadWCF.Product[]> GetProductsAsync(ActividadWCF.User user);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/GetProductsByCategoryID", ReplyAction="http://tempuri.org/IProductService/GetProductsByCategoryIDResponse")]
    ActividadWCF.Product[] GetProductsByCategoryID(ActividadWCF.User user);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/GetProductsByCategoryID", ReplyAction="http://tempuri.org/IProductService/GetProductsByCategoryIDResponse")]
    System.Threading.Tasks.Task<ActividadWCF.Product[]> GetProductsByCategoryIDAsync(ActividadWCF.User user);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/GetProductByID", ReplyAction="http://tempuri.org/IProductService/GetProductByIDResponse")]
    ActividadWCF.Product[] GetProductByID(ActividadWCF.User user);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/GetProductByID", ReplyAction="http://tempuri.org/IProductService/GetProductByIDResponse")]
    System.Threading.Tasks.Task<ActividadWCF.Product[]> GetProductByIDAsync(ActividadWCF.User user);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IProductServiceChannel : IProductService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class ProductServiceClient : System.ServiceModel.ClientBase<IProductService>, IProductService
{
    
    public ProductServiceClient()
    {
    }
    
    public ProductServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public ProductServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ProductServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ProductServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public ActividadWCF.ProductResponse InsertProduct()
    {
        return base.Channel.InsertProduct();
    }
    
    public System.Threading.Tasks.Task<ActividadWCF.ProductResponse> InsertProductAsync()
    {
        return base.Channel.InsertProductAsync();
    }
    
    public bool Authenticate(ActividadWCF.User user)
    {
        return base.Channel.Authenticate(user);
    }
    
    public System.Threading.Tasks.Task<bool> AuthenticateAsync(ActividadWCF.User user)
    {
        return base.Channel.AuthenticateAsync(user);
    }
    
    public ActividadWCF.Product[] GetProducts(ActividadWCF.User user)
    {
        return base.Channel.GetProducts(user);
    }
    
    public System.Threading.Tasks.Task<ActividadWCF.Product[]> GetProductsAsync(ActividadWCF.User user)
    {
        return base.Channel.GetProductsAsync(user);
    }
    
    public ActividadWCF.Product[] GetProductsByCategoryID(ActividadWCF.User user)
    {
        return base.Channel.GetProductsByCategoryID(user);
    }
    
    public System.Threading.Tasks.Task<ActividadWCF.Product[]> GetProductsByCategoryIDAsync(ActividadWCF.User user)
    {
        return base.Channel.GetProductsByCategoryIDAsync(user);
    }
    
    public ActividadWCF.Product[] GetProductByID(ActividadWCF.User user)
    {
        return base.Channel.GetProductByID(user);
    }
    
    public System.Threading.Tasks.Task<ActividadWCF.Product[]> GetProductByIDAsync(ActividadWCF.User user)
    {
        return base.Channel.GetProductByIDAsync(user);
    }
}
